--1.//
SELECT DEPARTMENT_NAME "학과명", CATEGORY "정원"
FROM TB_DEPARTMENT;

--2.//
SELECT DEPARTMENT_NAME  ||'의 정원은 ' || CAPACITY ||'명 입니다.'
FROM TB_DEPARTMENT;

--3.
SELECT STUDENT_NAME 
FROM TB_DEPARTMENT
WHERE ABSENCE_YN = 'N';


--4.


--5.//
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6.//
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


--7.//
SELECT STUDENT_NAME,STUDENT_NO
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8.//
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;
--9.//
SELECT CATEGORY
FROM TB_DEPARTMENT;

--10.//
SELECT STUDENT_NO, STUDENT_NAME,STUDENT_SSN, STUDENT_ADDRESS,ABSENCE_YN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '전주%' AND STUDENT_NO LIKE '_2%' AND ABSENCE_YN ='N' 
ORDER BY 2;
