--1.//
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;

--2.//

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___'; --AND PROFESSOR_NAME'__%';

--3.// 만나이만 계산 , 생일 지난거 안지난거 계산 SUBSTR EXTRACT 사용 생일 지난 만나이 계산은 CASE DECODE
SELECT PROFESSOR_NAME "교수이름",
CEIL(MONTHS_BETWEEN(SYSDATE,TO_DATE('19'  || SUBSTR(PROFESSOR_SSN,1,6),'YYYYMMDD'))/12 )나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1) = '1' 
ORDER BY 2;


--4.//

SELECT SUBSTR (PROFESSOR_NAME,2,3) "이름"
FROM TB_PROFESSOR;

--5.// 맞나

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - 
LPAD(SUBSTR(STUDENT_SSN, 1, 2), 4, '19') >= 20;


--6.//
SELECT TO_CHAR(TO_DATE(20201225),'DAY')
FROM DUAL;

--7.// ???? 2099/10/11 처럼 나오게해야함
ALTER SESSION SET NLS_DATE_FORMAT = 'RRRR/MM/DD';

SELECT TO_DATE('20991011', 'YYYY/MM/DD')"값1", 
TO_DATE('20491011', 'YYYY/MM/DD')"값2",
TO_DATE('19991011', 'RRRR/MM/DD')"값3", 
TO_DATE('20491011', 'RRRR/MM/DD')"값4"
FROM DUAL;



--8.//
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO  LIKE 'A%';

--9. // 
SELECT ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.// 흠
SELECT DEPARTMENT_NO "학과번호", COUNT(*) "학생수"  --학과별 학생 수 구하고 하기
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11.//
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12. // 한번 더 풀어보기
SELECT SUBSTR(TERM_NO, 1,4)"년도", ROUND(AVG(POINT), '1') "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1,4)
ORDER BY 1;

--13. //
SELECT DEPARTMENT_NO "학과 코드", COUNT(DECODE(ABSENCE_YN,'Y','Y')) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14.//
SELECT STUDENT_NAME 동일이름 , COUNT(*)"동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

--15.// 흠 너왜 4개 더 안나오는건데
SELECT  SUBSTR(TERM_NO, 1,4) 년도, SUBSTR(TERM_NO,5,4) 학기 ,ROUND (AVG(POINT),1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP (TERM_NO) 
ORDER BY 1;


