-- 1.//
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

-- 2.//
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY  STUDENT_SSN DESC;

-- 3.//
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번" ,STUDENT_ADDRESS"거주지 주소"
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS  LIKE '%경기도%'
AND NOT STUDENT_NO  LIKE 'A%'
ORDER BY STUDENT_NAME ASC;

-- 4.//

SELECT DEPARTMENT_NAME,DEPARTMENT_NO 
FROM TB_DEPARTMENT
ORDER BY 1;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ASC;

-- 5.//
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = 200402
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC ;

-- 6.// 여기부터 조인.. DEPARTMENT_NO 으로 조인
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

-- 7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NAME = D.CLASS_NAME);


--8.


