-- 1.//
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

-- 2.//
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY  STUDENT_SSN DESC;

-- 3.//
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번" ,STUDENT_ADDRESS"거주지 주소"
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS  LIKE '%경기도%'
AND NOT STUDENT_NO  LIKE 'A%'
ORDER BY STUDENT_NAME ASC;

-- 4.//

SELECT DEPARTMENT_NAME,DEPARTMENT_NO 
FROM TB_DEPARTMENT
ORDER BY 1; -- 이거 왜넣었지

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ASC;

-- 5.//
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = 200402
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC ;

-- 6.// 여기부터 조인.. DEPARTMENT_NO 으로 조인
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

-- 7.//
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2;

--8.// 
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
ORDER BY 2;

--9. 음악학과 학생들 평점 구하기
SELECT STUDENT_NO 학번, STUDNET_NAME 학생이름, ROUND(AVG(POINT),1) 전체평점
FROM TB_STUDENT
JOIN TB_GRADE ON (STUDENT_NO = STUDENT_NO);

--10.  A313047넣어야함 p034 박태환 경제학과 교수번호 이름으로 바꿔야함
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NO 지도교수
FROM TB_DEPARTMENT D
JOIN TB_STUDENT S ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR ON (PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';


--11.
SELECT STUDENT_NAME, TERM_NO TERM_NAME
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE ;