-- 1.//
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

-- 2.//
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY  STUDENT_SSN DESC;

-- 3.//
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번" ,STUDENT_ADDRESS"거주지 주소"
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS  LIKE '%경기도%'
AND NOT STUDENT_NO  LIKE 'A%'
ORDER BY STUDENT_NAME ASC;

-- 4.//

SELECT DEPARTMENT_NAME,DEPARTMENT_NO 
FROM TB_DEPARTMENT
ORDER BY 1; -- 이거 왜넣었지

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ASC;

-- 5.//
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = 200402
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC ;

-- 6.// 여기부터 조인.. DEPARTMENT_NO 으로 조인
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

-- 7.//
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2;

--8.// 
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
ORDER BY 2;

--9. // 음악학과 학생들 평점 구하기 흠
SELECT  STUDENT_NAME 학생이름, STUDENT_NO 학번, ROUND(AVG(POINT),1) 전체평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NAME, STUDENT_NO
ORDER BY STUDENT_NO;

--10.//  A313047넣어야함 p034 박태환 경제학과 교수번호 이름으로 바꿔야함

SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름,PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--11.//
SELECT STUDENT_NAME, TERM_NO TERM_NAME
FROM TB_STUDENT 
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO LIKE '2007%'
AND CLASS_NAME LIKE '인간관계론';


--12. 여기서 담당교수 배정 못받은애 넣기 LEFT 조인?
SELECT CLASS_NAME,DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

--13. // LEFT JOIN 위치 헷갈리네
SELECT STUDENT_NAME 학생이름 , NVL(PROFESSOR_NAME,'지도교수미지정') 지도교수
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR  ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME ='서반아어학과'
ORDER BY STUDENT_NO;


--14.평점 멍청아 다중조인 해빙? 그룹바이?
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME 학과, POINT 평점
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE USING (POINT);

--15. JOIN GROUP BY 사용
SELECT CLAS_NO, CLASS_NAME, (ROUDN(AVG(POINT,0))) 평점
FROM TB_CLASS
JOIN TB_CLASS;

-- 16.// 서브쿼리 사용

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM  TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
FROM TB_STUDENT
WHERE STUDENT_NAME LIKE '최경희');

-- 17. 국어 국문학과에서 총평점이 높은사람  JOIN 국문학과 001

SELECT POINT,CLASS_NO
FROM TB_GRADE;

SELECT DEPARTMENT_NAME,DEPARTMENT_NO 
FROM TB_DEPARTMENT;

SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT;

-- 18. JOIN, 서브쿼리 둘다
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1)
--FROM 

