-- 01 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서명, 직급, 입사일, 순위 조회

-- FROM 안에 먼저 만들어 버리고 SELECT로 필요한건거만 감싸서 FROM 안에 다박아버리기

SELECT EMP_ID, EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE,ROWNUM "순위"
FROM(
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE,E.SALARY*12 "연봉"
, E.SALARY*12+(E.SALARY*NVL(E.BONUS,0)) "보너스 포함 연봉",ROWNUM "순위"
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (J.JOB_CODE = E.JOB_CODE)
ORDER BY "보너스 포함 연봉" DESC)
WHERE ROWNUM < 6;



-- 02 부서별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서명, 부서별 급여 합계 조회
--(방법은 여러 가지..! 가급적으로 서브쿼리 사용해보세요!)
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON ()


-- 03 WITH을 이용하여 급여 합과 급여 평균 조회
SELECT SUM(SALARY), ROUND(AVG(NVL(SALARY,0)))
FROM EMPLOYEE;


WITH TOTAL AS(
SELECT SUM(SALARY), ROUND(AVG(NVL(SALARY,0)))
FROM EMPLOYEE
)
SELECT SUM(SALARY), ROUND(AVG(NVL(SALARY,0)))
FROM EMPLOYEE;


